import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from '../provider.js';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter.variable} ${inter.variable} antialiased`}
        >
          <Provider>

          {children}
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
